cjlee112/socraticqs2

doc/lti.rst, mysite/lti/admin.py, mysite/lti/migrations/0003_auto_20150625_0517.py, mysite/lti/migrations/0004_auto_20150716_0259.py, mysite/lti/models.py, mysite/lti/tests.py, mysite/lti/urls.py, mysite/lti/utils.py, mysite/lti/views.py, mysite/mysite/urls.py, mysite/templates/lti/error.html
@cjlee112 
This PR added create Course feature.
Course creation feature
=======================
Tool Consumer Instructor's can create Courses on Socraticqs2 Tool Provider remotely.
For this purpose it is necessary to enter `/lti/` url as `LaunchURL` on Tool Consumer External Tool edit page.
This PR added ability to handle such url's by looking at LTI request for `context_id`, `context_title`, `tool_consumer_instance_guid` and `roles` parameters.
To implement this we follow the next logic:
* First of all, we look at the `roles` LTI param of the user to decide whether the user can create courses or not.
* Next we look for `context_id` LTI param to search our CourseRef models. That models is a link between Course and particular University identified by ``context_id``.
* If we find a …
=> Create course PR

dev_requirements.txt, prod_requirements.txt, requirements.txt
@cjlee112 
python-social-auth version was freezed to 0.2.9 because of issue https://github.com/omab/python-social-auth/issues/671
This issue was fixed in https://github.com/omab/python-social-auth/pull/672 and have appeared in 0.2.12 version
So now we can move to python-social-auth 0.2.12 version
Issue #48
=> Update python-social-auth version to 0.2.12

README.rst, check-quality.sh, mysite/ct/fsm_plugin/randomtrial.py, mysite/fsm/fsm_base.py, mysite/fsm/fsm_plugin/testme.py, mysite/fsm/fsmspec.py, mysite/fsm/models.py, mysite/fsm/tests.py, mysite/fsm/utils.py, mysite/fsm/views.py
@cjlee112 
- quality.sh: implement new syntax `./check-quality.sh {pep8|pylint} {lti|psa|fsm|ct|mysite|all}` to allow to check `pep8|pylint` issues separately for all applications
- mysite/fsm/models.py: add `JSONBlobMixin` to move project to django/python best practices of making a readable and supportable code
- mysite/fsm/utils.py: move `get_plugin` func to utils.py to separate logic that not belong to `django models`
- README.rst: update according to new check-quality syntax
- all `fsm` app: change code according to pep8 and our code stype. Resolve important pylint warnings.
- remove unnecessary get_or_create method from ActivityLog
Issue https://github.com/cjlee112/socraticqs2/issues/52
Task on [trello](https://trello.com/c/h6K1UkxM/168-fsm-refactor-pep8-pylint-add-jsonblobmixin).
=> PR: pep8, pylint, code style and general refactor of fsm application

mysite/fsm/migrations/0002_auto_20150723_0243.py, mysite/fsm/models.py
@cjlee112 
PR to  add db indexes to fields by which filtering are performed
Rationalize:
- FSMGroup.group: index added due to `FSM.objects.filter(fsmgroup__group=groupName)` in ct/views.py:203
- FSMNode.name: index added due to `self.fsmnode_set.get(name=name)` in fsm/models.py:219
- FSMEdge.name: index added due to `self.fsmNode.outgoing.get(name=name)` in fsm/models.py:419 and `pageData.fsmStack.state.fsmNode.outgoing.filter(name=task)` in fsm/views.py:68
Issue https://github.com/cjlee112/socraticqs2/issues/58
Task on [trello](https://trello.com/c/Neg8vRQs/170-fsm-add-db-indexes).
=> ref(fsm): add db indexes to fields by which filtering are performed

mysite/ct/fsm_plugin/live.py, mysite/ct/templatetags/ct_extras.py, mysite/templates/ct/lessons.html
@cjlee112 
Changes:
- live.py: add select_UnitLesson_filter to filter input UnitLesson's
- ct_extras.py: add filter_input filter to pass unit_lesson to Node plugin_method for filtering
- lessons.html: apply filter_input filter to ul's at lessons.html:64
Issue https://github.com/cjlee112/socraticqs2/issues/74
=> fix(ct): fix issue #74

mysite/ct/tests/integrate.py, mysite/ct/views.py, mysite/templates/ct/lessons.html, mysite/templates/ct/lessons_table.html
@cjlee112 @VladimirFilonov 
There is a first attempt to implement Instructor UI for accessing Lesson versions.
In this PR Lessons search is changed a bit to return different Lesson version.
@cjlee112 in #97 you mention `Version tab` to show different Lesson version. Can you provide more clear description what you want to see? Because in current PR we are providing only search result changes and not Lessons representation changes in general.
Also I have to mention that tests for this new code will be provided only after #60 PR will be merged.
=> Instructor UI to access different Lessons version during search

dev_requirements.txt, mysite/psa/migrations/0003_auto_20150420_0308.py, mysite/psa/migrations/0004_customcode.py, prod_requirements.txt, requirements.txt
Changes:
- change ForeignKey in `psa` application to look on `social_auth` instead of `default` `python-social-auth default Django app` (issue #993)
=> chore(python-social-auth): update library version to `0.2.21`

mysite/ct/tests/views.py, mysite/ct/views.py
Disables creation of error models for orct lessons. commented out 2 lines in ct.views.concept_lessons view.
Please take a look into this ticket https://github.com/cjlee112/socraticqs2/issues/194
=> fix(ct:views): Stop auto-creation of error models for new ORCT question

mysite/ct/tests/views.py, mysite/ct/views.py
When user move unitLesson form one courselet to another one we have to remove all concept links which are linked to moved unit lesson
Issue #378
=> fix(issue#378): When user move unitLesson we have to drop out linked ConceptLinks

mysite/lti/models.py, mysite/lti/tests.py
Fixes `MultipleObjectsReturned` bug when trying to `get_or_create` Student Role for LTI session
=> Fix/issue#255 

mysite/lti/models.py, mysite/lti/tests.py
Issue #455 
Problem: different LTI users are connected to the same Django user
Solving: change username generation logic
=> Fix/issue#455 - The same username for LTI Users

mysite/chat/urls.py, mysite/chat/views.py, mysite/templates/chat/chat_history.html, mysite/templates/lms/course_page.html
[ISSUE-554](https://github.com/cjlee112/socraticqs2/issues/554)
Issue
===
When user open chat history we should show different HTML.
Solution
===
Added new template for view chat history
=> [ISSUE-554] The 'smthng went wrong' error appears when open courselet which just has been created

mysite/chat/models.py
If chat has no last_modify_timestamp we should get last message and assign it's timestamp to this field.  Messageges should be filtered out to not include messages with timestamp NULL.
=> [issue #549] Fix error appears when trying to open finished courselet

mysite/chat/api.py, mysite/chat/fsm_plugin/chat_add_lesson.py, mysite/chat/models.py, mysite/chat/serializers.py, mysite/chat/urls.py, mysite/fsm/mixins.py, mysite/templates/chat/add_unit_chat.html
* Adds new node in chat_add_lesson FSM - UNIT_NAME_TITLE
* Changes in mixins to show DIVIDER when user in START node
* Adds new method in Message model to get html for sidebar
* Adds new chat url for progress (only for add unit by chat) and handler for progress
* Adds 2 serializers - for progress and for message to serialize it to breakpoint
=> [ISSUE #512]: now when user add units by chat he will see steps (questions) in sidebar

mysite/ctms/middleware.py, mysite/ctms/views.py, mysite/templates/ctms/includes/sidebar.html
fix(sidebar_middleware): Fixed logic related to remembering Course/Courselet/Unit ids in sidebar MW
Changes in sidebar templates to make URLs (Courselet) more consistent
Small fix in ctms/views.py
=> fix(sidebar_middleware): Fixed logic related to remembering Course/Courselet/Unit ids in sidebar MW

mysite/lms/views.py
When filter courselet's chats in lms/views.py:CourseView is_live parameter must be False.
=> [ISSUE #575] Fix courselet progress when user start new live session (progress of courselet come to be full).

mysite/chat/api.py, mysite/chat/models.py, mysite/chat/tests/tests.py, mysite/chat/views.py, mysite/lms/tests.py, mysite/templates/chat/main_view.html
Now when user load page chat_enroll it will not create new chat. New chat will be created only after JS ajax request to api endpoint. This endpoint will create new chat and start FSM.
It's first version of implementation, next I will remove all comments. I need them now to understand what changes I've done
=> chat initialization process moved to JS

mysite/templates/pages/faq_item_plugin.html
Added md2html into django cms FAQ plugin HTML
=> [ISSUE 572]: Added md2html into FaqItemPlugin HTML

mysite/chat/views.py, mysite/templates/chat/main_view.html
Is described in ticket #585 
If chat_id is present in template context and it's not None (not empty, not zero etc) - if fsmstate is not empty show button "Lets get started", if fsmstate is empty (not present in context) show button "View history".
If no chat_id in context - show chat sessions and "create new chat session" button.
=> fix(issue#585): Don't need to show "New Chat Session" when view history.

mysite/templates/ct/errors.html
The problem is described here #618
Rework error models search template to show EM like we do it for UL, if they have the same treeID we wrap them up and show button Versions.
=> fix(issue#618): Changes in showing search results of error models. Show them as UL with 'Versions' button

mysite/ct/models.py, mysite/ct/tests/models.py
When someone deleted UnitLesson associated with error model from concept, it returns 500 error.
Wrap method Concept.get_url with try\except. In usual way it will return path, as desired, in case of exception (if no UL associated with Concept) it will return '#' to avoid of crashing the whole page.
=> fix(issue#621): Fix to handle case when Concept doesn't have associated UnitLesson. (Not as part of Unit but as ErrorModel or so)

mysite/accounts/models.py, mysite/analytics/tasks.py
is described here #687 
Now field timezone has choices with all avialable timezones, and in case for old profiles with already set incorrect tz it will use default TZ from settings file.
=> fix(issue#687): Fix for issue #687 to avoid incorrect timezone in user profile.

mysite/accounts/models.py, mysite/lti/tests.py, mysite/lti/views.py
is described here #686 
When user log in through lti - get user's location using pygeoip and remember timezon in Profile.timezone
=> fix(issue#686): When user login through lti we create profile (if not exist) and store tz
