dev_requirements.txt
mysite/ct/views.py
mysite/fsm/views.py
mysite/mysite/settings/defaults.py
prod_requirements.txt
requirements.txt

@cjlee112 
This PR is about caching using memcached.
To merge this PR you need to merge https://github.com/cjlee112/socraticqs2/pull/43 firstly.
After that I will do rebase on your master branch and you will see only one new commit to merge - https://github.com/cjlee112/socraticqs2/commit/8034197d1ef67918147a40791d243142d73f8dec
@auraz

PR add caching using Memcached

---

dev_requirements.txt
doc/devintro.rst
mysite/ct/migrations/0016_auto_20150626_0301.py
mysite/ct/models.py
mysite/lti/tests.py
mysite/mysite/settings/local_conf_example.py
prod_requirements.txt
requirements.txt

@cjlee112 
In this PR we are moving to Postgresql.
Changes:
- I have added Postgresql setting to local_conf_example.py to set DB username and password.
- max_length of some fields has been increased because of fixture data (e.g. `Lesson.title`) that appeared to be bigger than our old max_length constraints.
- lti/tests.py are changed because of postgresql id's autoincrement feature.
This PR must be merged after https://github.com/cjlee112/socraticqs2/pull/44
After merge of https://github.com/cjlee112/socraticqs2/pull/44  I will do rebase on your master branch and you will see only one new commit to merge - https://github.com/cjlee112/socraticqs2/commit/5943921a564725b674a4edcaee1352a4fdf1e998
@auraz

PR to move to Postgres

---

mysite/fsm/fsm_base.py

@cjlee112 
Changes:
- in FSMStack `__init__` use select_related to fetch `fsmNode` and prefetch_related to fetch `outgoing` egdes for using in line :30 `for edge in self.state.fsmNode.outgoing.all()`
- in FSMStack `push` use select related to fetch `startNode` for use in line :70 `fsm.startNode`
- in FSMStack `resume` avoid addition DB query by equating not user objects but user id's
PR contains fsm app QuerySet improvements:
* in FSMStack `__init__` use select_related to fetch `fsmNode` and prefetch_related to fetch `outgoing` egdes for using in line [:20](https://github.com/raccoongang/socraticqs2/blob/fsm_optimization/mysite/fsm/fsm_base.py#L30) -> `for edge in self.state.fsmNode.outgoing.all()`
* in FSMStack `push` use select_related to fetch `startNode` for use in line …

ref(fsm): fsm app QuerySets optimization

---

doc/devintro.rst
doc/fsm.rst
mysite/dumpdata/debug-wo-fsm.json
mysite/fsm/management/commands/fsm_deploy.py

@cjlee112 
Changes:
- mysite/dumpdata/debug-wo-fsm.json: add new fixture w/o fsm(s) instances
- mysite/fsm/management/commands/fsm_deploy.py: add fsm_deploy cmd to deploy fsm via fsm specifications
- doc/fsm.rst: update fsm docs accordingly
- doc/devintro.rst: change fixture filename according to new fixture file
Issue https://github.com/cjlee112/socraticqs2/issues/57
Task on [trello](https://trello.com/c/11ywEZdN/190-django-manage-command-for-deploy-fsm-modules).
@dixon-che FYI

PR: FSM deploy manage cmd

---

.gitignore
dev_requirements.txt
fab_settings.py.example
fabfile.py
fabfile/__init__.py
fabfile/db/__init__.py
prod_requirements.txt
requirements.txt

@cjlee112 
Add Fabric to automate project deployments.
New files:
- fab_settings.py.example: Fabric settings file
- fabfile.py: Fabric main fabfile
Issue https://github.com/cjlee112/socraticqs2/issues/59
Task on [trello](https://trello.com/c/oenvmmRH/192-add-fabric-tool-to-project).

Fabric deploy

---

mysite/ct/views.py

@cjlee112 
Description:
- Fix missing import KLASS_NAME_DICT from fsm.models
Issue #70

PR fix issue #70

---

mysite/ct/views.py

@cjlee112 
PR to fix wrong fsm_status path on line ct/views.py:233
Issue #75

fix(ct): fix issue #75 about wrong fsm_status path

---

mysite/psa/pipeline.py
mysite/templates/psa/legacy_backends.html
mysite/templates/psa/modal.html
mysite/templates/psa/social_backends.html

@cjlee112 
Changes:
- add {{ next }} variable to legacy_backends and social_backends templates and to a modal template
- add passing ``next`` variable across custom email validation process
Issue https://github.com/cjlee112/socraticqs2/issues/78

fix(psa): fix redirect url issue

---

mysite/ct/views.py

@cjlee112 
Change referer checking login to make logic more universal.
Issue https://github.com/cjlee112/socraticqs2/issues/81

fix(ct): fix referer finding logic in ct/views.py:158

---

mysite/ct/tests.py

@cjlee112 
Add HTTP_ORIGIN to self.client.post in check_post_get method.
Also add check for incoming url to contain http host and protocol as HTTP_REFERER and HTTP_ORIGIN have.
Issue #81

PT to update tests according to new referer checking logic

---

mysite/ct/ct_util.py
mysite/ct/views.py
mysite/fsm/views.py
mysite/mysite/settings/defaults.py
mysite/mysite/views.py

@cjlee112 
[PR to move from per-site caching to per-view caching]
There is one view that can be cached carefully so I propose to move to per-view caching strategy.
Issue https://github.com/cjlee112/socraticqs2/issues/71

Fix issue#71 Caching only selected views and functions 

---

mysite/templates/ct/portal.html

@cjlee112 
Add  `<div class="container">` as a wrapped around the fsm block and content block in portal.html

Improve stylesheet PR

---

doc/devintro.rst
prod_requirements.txt

@cjlee112 
Add `Celery` section into docs, update Pre-requisites section.
Add `gunicorn` to prod_requirents.txt
Issue to discuss
------------
There is no `admin` user in production DB snapshot.
So I need to change user to deploy FSM in `fsm_deploy` manage command to `foobaron` (presented in DB) or create `admin` user.

PR to add gunicorn to prod_requirements.txt, update docs

---

mysite/ct/templatetags/ct_extras.py

@cjlee112 
Fix creation of static url for S3 storage.

PR to fix static ur for S3 storage

---

mysite/psa/models.py

@cjlee112 @maxsocl 
Issue appeared on private browser tab.
Also optimised user sessions tracking - avoid non necessary checking.

fix(psa): fix UserSession creation signal

---

mysite/mysite/context_processors.py
mysite/mysite/settings/defaults.py
mysite/mysite/settings/developer_conf.py
mysite/mysite/settings/local_conf_example.py
mysite/templates/base.html
mysite/templates/google-analytics.html

@cjlee112 @maxsocl 
Added GoogleAnalytics support 
For using GA we need specify GOOGLE_ANALYTICS_CODE settings
If GOOGLE_ANALYTICS_CODE isn't specified in settings, then JavaScript tracking snippet won't be added.

Added GoogleAnalytics JavaScript tracking snippet

---

mysite/ct/exceptions.py
mysite/ct/models.py
mysite/ct/sourcedb_plugin/wikipedia_plugin.py
mysite/ct/views.py
mysite/templates/ct/wikipedia.html

@cjlee112 @VladimirFilonov 
This PR adds fix for issue #120.
Tests will be added only after PR #60 will be merged.

Fix for issue#120

---

mysite/fsm/admin.py
mysite/fsm/migrations/0003_auto_20151030_0416.py
mysite/fsm/models.py

@cjlee112 @VladimirFilonov 
Changes:
- add blank=True to several fields to allow to correctly edit/create models
- add `__unicode__` method to several FSM models to create clear representations for models
Issue https://github.com/cjlee112/socraticqs2/issues/109

Fix issue#109 - add fsm models into Django admin UI to allow to edit FSM's

---

mysite/ct/admin.py
mysite/ct/forms.py
mysite/ct/migrations/0017_auto_20151012_0421.py
mysite/ct/migrations/0019_auto_20160614_0335.py
mysite/ct/models.py

@cjlee112 @VladimirFilonov 
Add auto setting initial values to couple of models in Admin page.
Fix blank attrs that prevents to create some models from admin.
Issue https://github.com/cjlee112/socraticqs2/issues/89
Task [trello](https://trello.com/c/DlSyfdDU/222-admin-blank-attributes-in-models)

Fix issue#89 - added blank attributes

---

mysite/ct/views.py
mysite/templates/ct/lessons_table.html

Another changes:
- show author username if there is not FullName
- code style changes in `ct/views.py`

fix(lesson_table.html): show correct branch commit message, commit time

---

mysite/ct/api.py
mysite/ct/serializers.py
mysite/ct/urls.py
mysite/ct/views.py
mysite/mysite/urls.py

Add ability to get Course reports via API

Course report api

---

mysite/ct/admin.py

Changes:
- use `raw_id_fields ` for `Response ` and `StudentError ` models to decrease response time

fix(ct.admin): fix issue#195 - nginx 504 error

---

mysite/ct/admin.py
mysite/ct/models.py

Adds Liked model to admin UI, adds filter by username and lesson name.

fix(ct.admin): Added Liked model into admin UI.

---

mysite/chat/views.py

fix(chat): fix `will learn` and `need to know` section logic

---

mysite/chat/fsm_plugin/additional.py
mysite/chat/fsm_plugin/chat.py

Fix #344 
Except message "You have completed 3 of 10" because we need to implement progress in frontend.

fix(chat): change text for additional and for chat FSM END node

---

mysite/ct/models.py
mysite/ct/tests/views.py
mysite/ct/views.py

Fixed Forbidden error template instead of raise Key error `KeyError: 'user not in this class'`
@z4y4ts please review

fix(issue#261): Fixed Forbidden error template

---

mysite/chat/fsm_plugin/live_chat.py
mysite/ct/fsm_plugin/live.py
mysite/pytest.ini

Added functions into live FSM to handle exceptionalCancel and quit.
Issue #256 
@z4y4ts please review

Handle case when Instructor `Cancel` activity

---

mysite/chat/admin.py
mysite/chat/api.py
mysite/chat/fsm_plugin/chat_add_lesson.py
mysite/chat/fsm_plugin/courselet_preview.py
mysite/chat/migrations/0007_chat_is_preview.py
mysite/chat/models.py
mysite/chat/services.py
mysite/chat/urls.py
mysite/chat/views.py
mysite/ct/admin.py
mysite/ctms/forms.py
mysite/ctms/migrations/0002_auto_20170302_0658.py
mysite/ctms/urls.py
mysite/ctms/views.py
mysite/fsm/mixins.py
mysite/templates/chat/add_unit_chat.html
mysite/templates/ctms/course_detail.html
mysite/templates/ctms/courselet_detail.html
mysite/templates/ctms/unit_edit.html

Added basic functionality for adding units, templates, urls,  views, functionality for adding error models (formset, view).
branch: feature/mvp_instructor
fixes issues:
- #312 
- #309

feat(mvp_instructor): Added basic functionality for adding units, preview courselets

---

mysite/ct/views.py

fix(issue#377): Fixed CommonDisambiguationError when user link errorModel to concept

---

mysite/api/v0/views.py

fix issue #412 
Added get_object_or_404 from rest_framework.generics

fix(issue#412): Fixes issue #412 - AttributeError at /api/v0/courses/111/responses/ and /api/v0/courses/111/errors/

---

mysite/psa/forms.py

Password should contain 6 chars, 1 capital char an 1 digit

fix(issue#391): Fixed issue #391 - added password regex validator

---

mysite/templates/accounts/password_reset_form.html

added links to login and signup page on password_reset page

fix(issue#292): added links to login and signup page on password_reset page

---

mysite/ct/admin.py
mysite/ctms/views.py
mysite/templates/ctms/unit_edit.html

fix issue #388 
Now user can add ORCT Unit

fix(issue#388): Fixed issue #388, did come changes in templates

---

mysite/chat/views.py

Fix on Preview action exception create_new_chat() takes exactly 3 arguments

fix(issue#387): Fixed issue #387 - On Preview action exception

---

mysite/templates/ctms/ctms_base.html

fix issue #389 : Added link to open chat to add new units in courselet

fix(issue#389): Added link to open chat to add new units in courselet

---

mysite/accounts/views.py
mysite/psa/forms.py
mysite/psa/views.py

Fix issue #390  -Create instructor for user if not exist yet

fix(issue#390): Fixed issue #390 - On Preview action exception

---

mysite/templates/psa/new_custom_login.html

Fix issue #392 - Adds links to signup and reset password on login page

fix(issue#392): Adds links to signup and reset password on login page

---

mysite/mysite/urls.py
mysite/psa/custom_backends.py
mysite/psa/views.py

fix(issue#421): Added message for case when user click on confirmation link not first time
If user click link first time (logged in/not logged in - pipeline is logging user in) - it will log him in and redirect to profile page
If user click more than 1 time on confirmation link - if logged in - will be redirected to profile page, if not - to login page.

Fix/issue#421: Added message for case when user click on confirmation link not first time

---

mysite/accounts/forms.py
mysite/ctms/forms.py
mysite/ctms/tests.py
mysite/ctms/urls.py
mysite/ctms/views.py
mysite/templates/accounts/settings.html

Fixed delete user functionality, added some JS to handle submit button on AccountSettings page in DeleteUserForm
Fixed ctms tests to run them with pytest
Changes in mostly all querysets in ctms which are related to get object (only Instructor can get access to ctms, only owner can change/delete/view course/courselet/unit (s).

fix(ctms/tests, issue#435, issue#428): Fixed ctms tests. Fixed issue#435, issue#428

---

mysite/accounts/views.py
mysite/ctms/middleware.py
mysite/ctms/views.py

Changes in SidebarMiddleware class to remember current course/courselet/unit and show them in sidebar in not CTMS pages.

feat(sidebar_memory): Changes in SidebarMiddleware class to remember course/courselet/unit

---

mysite/chat/models.py
mysite/chat/urls.py
mysite/chat/views.py
mysite/lms/static/css/app.css
mysite/lms/static/sass/components/_course-content.scss
mysite/lms/tests.py
mysite/lms/views.py
mysite/templates/lms/course_page.html

User can redo courslet, adds some tests to test this functionality
Fix issue #259 
@z4y4ts please review

fix(redo_courslet): 

---

mysite/chat/migrations/0007_chat_last_modify_timestamp.py
mysite/chat/migrations/0008_chat_last_modify_timestamp.py
mysite/chat/models.py
mysite/lms/tests.py
mysite/templates/lms/course_page.html

fix(issue#268): Added field last_modify_timestamp to Chat model, add methods to calculate spent time and format it.

fix(issue#268): Added field last_modify_timestamp to Chat to calculate spent time.

---

mysite/chat/models.py
mysite/chat/tests/tests.py
mysite/ct/forms.py
mysite/ct/migrations/0021_lesson_add_unit_aborts.py
mysite/ct/models.py

feat(ct/chat): allow instructors to ajust EMs displaying - not include Unit EMs for Lessons
Instructors should be able to select EMs display options.

Options to not show EMs

---

mysite/lti/models.py
mysite/lti/tests.py
mysite/lti/utils.py

Changes:
- using user_id, tool_consumer_instance_guid, lis_person_sourcedid to cmpile hashed username

Change username creation logic

---

mysite/ct/migrations/0022_auto_20170527_1519.py
mysite/ct/models.py
mysite/ct/tests/models.py
mysite/ct/tests/views.py
mysite/ct/views.py
mysite/lti/tests.py
mysite/templates/ct/unit_answers.html

Issue: #501 
Notes:
- unique together has been added for Role model so duplicated Roles should be removed from stage/dev or prod while deploying.

feat(ct): add pagination feature to Answers tab in Courselet page

---

mysite/chat/api.py
mysite/chat/fsm_plugin/chat.py
mysite/chat/models.py
mysite/chat/tests/tests.py
mysite/fsm/mixins.py

Implementation of Confidence asking in a chat.

Feature/issue#343 Confidence

---

mysite/chat/api.py
mysite/chat/fsm_plugin/live_chat.py
mysite/chat/models.py
mysite/chat/serializers.py
mysite/chat/services.py
mysite/ct/fsm_plugin/livestudent.py
mysite/ct/views.py
mysite/fsm/fsm_base.py
mysite/fsm/mixins.py
mysite/fsm/models.py

Refactoring to check FSM node names and FSM names

fix(old_chat_confidence): Fix to make old chats work well with new FSM.

---

mysite/psa/forms.py
mysite/psa/views.py

Users were able to login using one time login (email login) if there's a user with empty email in system.

fix(issue#532): Fix issue#532. Added validation in psa.complete function to not allow to pass empty email

---

mysite/templates/chat/main_view.html

After adding changes about history live session is broken.
###
This PR fixes it.

[ISSUE #562]: Fix broken live session after adding history changes

---

mysite/chat/api.py
mysite/mysite/settings/dev.py
mysite/mysite/urls.py
mysite/templates/pages/banner_plugin.html
mysite/templates/pages/landing_page.html

Add menu on the top of the page, add django-debug toolbar in this branch (only for local machines), fix banner_plugin - add lost button link

fix(cms_landing_page): Fixes for landing page

---

mysite/pages/static/pages/css/main.css
mysite/pages/static/pages/sass/main.scss
mysite/templates/pages/banner_plugin.html
mysite/templates/pages/landing_page.html

Added link to Courses Dashboard into top menu, removed not needed class from Signup button on landing page.

fix(landing): Adds menu item and fix Signup button on landing page

---

mysite/ct/urls.py
mysite/ct/views.py
mysite/templates/ct/edit_course.html

New instances of a courselet for different quarters/semesters
###Solution:
Now instructors can make a deep copy of course with courselets\units. Also it make copy of Role objects.

[ISSUE #573] Added ability to copy course

---

mysite/ct/views.py

When UnitLesson has parent and this parent also has parent code failed.
Order UnitLessons by parent, firstly handle with no parent, then with parent__parent__isnull=True and so on. Added DEEP_LVLS variable to be able to change max deep.

[ISSUE #573]: Small fixes to make code more stable

---

mysite/chat/views.py
mysite/templates/chat/main_view.html

Is described here #595 
Added ordering for chat session, changed showing chat session name from (was timestamp, now last_modify_timestamp)

fix(issue#595): Fix issues listed in ticket #595.

---

mysite/ct/management/commands/clone_course.py
mysite/ct/models.py

Fix for clone course

---

mysite/mysite/urls.py
mysite/psa/templatetags/social_tags.py
mysite/psa/views.py
mysite/templates/admin/auth/user/change_form.html

Added admin view an a button in admin UI (o change user page) to allow users who are in group CAN_LOGIN_AS_OTHER_USER to login as other users (students for example)

[ISSUE #354] instructor wants to see from a specific student's view

---

mysite/ct/management/commands/clone_course.py
mysite/ct/models.py

ISSUE #611 : Resources were not copied the cloning course
SOLUTION: Add copying specific UnitLessons which are Resources.

[ISSUE #611]: Fixes to copy course Resources

---

mysite/ct/models.py

is described here #664 
Check title len before save instance to DB and in case it's longer than allowed - cut it down.

fix(issue#664): If len of course title after copying it is more than allowed - cut it down to allowed len.

---

mysite/ct/migrations/0023_course_copied_from.py
mysite/ct/models.py
mysite/templates/ct/course.html

The problem is described here #665 
Added new field (FK to Course) into Course model, and when we copy course - fill this field.

Fix/issue#665: Add link to course from this was copied.

---

mysite/mysite/settings/base.py
mysite/mysite/settings/local_example.py
requirements/base.txt

Add Sentry integration into the project

[SENTRY] Integration

---

mysite/accounts/models.py
mysite/fsm/mixins.py
mysite/lti/tests.py
mysite/lti/views.py

Features
----
* CR-12 TZ improvements
* CR-13 The TZ isn't updated when login through LTI

[Code freeze] Sprint-2
